# Travis CI testing configuration

language: node_js

# Install fossa-cli
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

# Use latest version of Node.js
node_js:
  - node

# Cache node_modules after testing
cache: npm

# Test application and run analysis with fossa-cli afterwards
script:
  - npm test
  - fossa init
  - fossa analyze
  - fossa test
